
version: "3.8"

services:
  postgres:
    container_name: int_db
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-test
    command: redis-server

  int_app:
    container_name: int_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    read_only: false
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

  app-migrations:
    container_name: int_migrations
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file: .env
    read_only: false
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/setup-db.sh

volumes:
  postgres-data:
  redis-data:
  app:

networks:
  app: